{
 "title": "HyperNode - Polygon",
 "description": "HyperNode Info",
 "tags": [ "HyperNode" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up{}, job)" } },
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview【JOB：$job】",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} / (node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "HyperNode",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "gRPC Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_method=\"Relay\", job=~\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "gRPC AVG throughput per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_method=\"Relay\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "gRPC errors rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{job=~\"$job\", grpc_method !~ \"Ping|Relay\"}[1m])",
     "legendFormat": "{{grpc_code}}{{instance}}"
    }
   ]
  },
  {
   "title": "Polygon Bor",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Polygon Heimdall",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 10 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_block" }
   ]
  },
  {
   "title": "Blocks per min",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "increase(chain_head_block[1m])", "legendFormat": "Polygon Bor" }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Blocks per min",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_latest_block_height{job=~\"$job\"}[1m])",
     "legendFormat": "Polygon Heimdall"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_peers" }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=~\"$job\"}"
    }
   ]
  }
 ]
}