scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'hyper-node-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'hyper-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8899']
  - job_name: 'klaytn'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:31275']
